services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: gemma_vllm_server
    restart: unless-stopped
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - VLLM_WSL2_ENABLE_PIN_MEMORY=1
    ports:
      - "8000:8000"
    volumes:
      - huggingface_cache:/root/.cache/huggingface
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    command:
      - "--model"
      - "neuralmagic/gemma-2-2b-it-FP8"
      - "--gpu-memory-utilization"
      - "0.80"
      - "--max-model-len"
      - "4096"
      - "--enforce-eager"
      - "--enable-prefix-caching"
      - "--port"
      - "8000"
      - "--host"
      - "0.0.0.0"
      - "--trust-remote-code"

volumes:
  huggingface_cache:

